services:
  - type: web
    name: ambulance-service
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DB_URL
        fromDatabase:
          name: ambulance-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: ambulance-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ambulance-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
    dockerContext: .
    dockerfilePath: Dockerfile

databases:
  - name: ambulance-db
    databaseName: ambulance_service
    user: ambulance_user
    plan: free
